name: "Allocate Security Identifiers"
on: 
  workflow_dispatch:
  schedule:
    - cron: '12 */2 * * MON-FRI'

concurrency:
  group: allocate-security-identifiers
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  allocate-security-identifiers:
    name: "Allocate Security Identifiers"
    runs-on: runs-on=${{ github.run_id }}/runner=medium-arm
    container:
      image: python:3.13-alpine
    permissions:
      contents: write
    steps:
      - name: Install OS dependencies
        run: apk add --no-cache git openssh taplo sqlite tar zstd curl oras-cli bash date grype
      - name: Configure git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install python dependencies
        run: pip install git+https://github.com/anchore/security-cli
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
        with:
          ssh-key: ${{ secrets.SECURITY_IDENTIFIERS_CI_PUSH_TOKEN }}
      - name: Allocate security identifiers
        run: anchore-security-cli id allocate --data-path data
      - name: Run TOML formatting
        run: taplo format
      - name: Run TOML schema validation
        run: taplo validate --schema file:${PWD}/schema/0.1.0.schema.json
      - name: Run TOML formatting validation
        run: taplo format --check
      - name: Commit changes
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          ./scripts/commit.sh
          git push