name: "Publish Security Identifiers Index (development)"
on: 
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: publish-security-identifiers
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  publish-security-identifiers:
    name: "Publish Security Identifiers Index (development)"
    runs-on: runs-on=${{ github.run_id }}/runner=medium-arm
    container:
      image: python:3.13-alpine
    permissions:
      contents: write
      packages: write
    steps:
      - name: Install OS dependencies
        run: apk add --no-cache git taplo sqlite tar zstd curl oras-cli bash
      - name: Configure git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install python dependencies
        run: pip install git+https://github.com/anchore/security-cli
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
        with:
          persist-credentials: false
      - name: Render and publish the security identifiers sqlite index
        run: |
          anchore-security-cli -v id index render --data-path=data -o=${{ runner.temp }}/security-identifiers-index
          anchore-security-cli -vvv id index publish --index-dir=${{ runner.temp }}/security-identifiers-index --deploy-to=development