name: "Validations"
on:
  # needed for publishing commit images on the main branch
  push:
    branches:
      - main

  # needed when running from forks
  pull_request:

permissions:
  contents: read

jobs:
  validate-schema:
    name: "Validate Schema"
    runs-on: runs-on=${{ github.run_id }}/runner=medium-arm
    container:
      image: python:3.13-alpine
    permissions:
      contents: read
    steps:
      - name: Install OS dependencies
        run: apk add --no-cache taplo
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
      - name: Run schema validation
        run: taplo validate --schema file:${PWD}/schema/0.1.0.schema.json
      - name: Run format validation
        run: taplo format --check